apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cmwatcheroperator
rules:
- apiGroups:
  - ''
  - 'batch.github.com'
  - 'apps'
  resources:
  - 'configmapwatchers'
  - 'configmaps'
  - 'deployments'
  verbs:
  - 'get'
  - 'update'
  - 'list'
  - 'watch'
